---
# tasks file for acuo-compose

- name: clone acuo-devops rep
  git: 
    repo: https://github.com/anaxo-io/acuo-devops.git
    dest: /home/ubuntu/projects
    version: develop
    update: yes
    clone: no

- name: copy deploy script
  copy: src=deploy.sh dest=/home/ubuntu/projects/deploy.sh mode=0755

- name: deploy using docker compose
  command: /home/ubuntu/projects/deploy.sh "{{ app_name }}"
  register: myoutput
